#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [2]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [2]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [ ]:
help(np.add)

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [4]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [2]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [4]:
arr = np.arange(51)
arr[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [4]:
arr = np.arange(51)
np.flip(arr)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [36]:
a = np.array([1, 2, 3, 4])
np.append(a, 5)

array([1, 2, 3, 4, 5])

In [61]:
a = np.empty(0)
a

array([], dtype=float64)

In [62]:
np.append(a, 9)

array([9.])

#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [5]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի ինդեքսները:

In [63]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.where(arr!=0)[0]

array([0, 1, 4])

#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [66]:
arr = np.random.randint(1, 21, (3, 3, 3))
arr

array([[[ 1, 18,  9],
        [14, 20, 16],
        [11,  9,  8]],

       [[ 4,  7, 18],
        [ 4,  5, 18],
        [12, 13, 17]],

       [[14, 20, 10],
        [19, 16,  1],
        [ 5, 16,  3]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [8]:
arr = np.random.rand(10, 10)
print(arr)
np.amax(arr), np.amin(arr)

[[0.3794261  0.15610676 0.21886018 0.46930065 0.33236437 0.04416836
  0.01870135 0.49172259 0.7495355  0.89672178]
 [0.23851751 0.9514817  0.08912603 0.35918027 0.69367633 0.65402844
  0.65203129 0.3367293  0.50553129 0.96052172]
 [0.78549277 0.31633907 0.66771779 0.41637179 0.51406579 0.99026012
  0.42607195 0.19959727 0.11799744 0.67063044]
 [0.31618969 0.79709751 0.39099996 0.68636165 0.93725422 0.67559672
  0.34052038 0.71197492 0.9038478  0.78448921]
 [0.82170747 0.21464518 0.4024305  0.73837221 0.35286419 0.99414295
  0.72667815 0.81200802 0.24556895 0.36103314]
 [0.3124295  0.76287334 0.56337361 0.43598662 0.50358847 0.7008103
  0.8647889  0.77180031 0.4252589  0.8262759 ]
 [0.20366388 0.55351623 0.02092314 0.03350825 0.79239523 0.3275259
  0.72873965 0.9280522  0.35730933 0.06127814]
 [0.15815275 0.60816977 0.18961965 0.38748367 0.06326743 0.7068895
  0.4191192  0.29021627 0.21201536 0.67430211]
 [0.39626195 0.78850565 0.92070509 0.97281466 0.41080308 0.58967241
  0.47648178 0.

(0.9941429474078032, 0.01194284482605068)

#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [11]:
arr = np.random.rand(30)
print(arr)
np.mean(arr)

[0.8346402  0.46586884 0.50398048 0.7118153  0.59319559 0.54072124
 0.44911409 0.79746417 0.78446066 0.12999157 0.77977828 0.95490442
 0.05507697 0.03345497 0.45421119 0.4072819  0.37756646 0.90764502
 0.83327399 0.45824976 0.88991072 0.21535028 0.39182542 0.49320247
 0.37114718 0.61670365 0.66761454 0.84067314 0.30119526 0.22721102]


0.5362509582240953

#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [72]:
arr = np.arange(11)
arr[(arr>3) & (arr<8)]

array([4, 5, 6, 7])

#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 0-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [11]:
arr = np.random.randint(1, 11, 20)
print(arr)
arr[arr<5] *= 2  #arr[arr<5] = arr[arr<5]*2
print(arr)

[ 4  2 10  6  6  5  4  4  7  7  1  2  3 10  3  7  9  5  9 10]
[ 8  4 10  6  6  5  8  8  7  7  2  4  6 10  6  7  9  5  9 10]


#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [12]:
arr = np.array([1, 5, 6, 2, -2, 23, 45])
np.where(arr%2==0)

(array([2, 3, 4]),)

#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [79]:
arr = np.arange(1, 21)
print(arr)
arr[arr%3==0]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 3,  6,  9, 12, 15, 18])

#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [22]:
arr = np.arange(5)
print(arr)
np.tile(arr, (5, 1))

[0 1 2 3 4]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 17. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in the array.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի մեծագույն ու փոքրագույն արժեքները։

In [19]:
arr = np.array([[0, 1], [2, 3]])
np.amin(arr), np.amax(arr)

(0, 3)

#### 18. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in each column.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի սյուների մեծագույն ու փոքրագույն արժեքները։

In [15]:
arr = np.array([[0, 1], [2, 3]])
np.amin(arr, axis=0), np.amax(arr, axis=0)

(array([0, 1]), array([2, 3]))

#### 19. Create  numpy array of size 10 filled with integers of your choice. Compute mean, median, standard deviation and variance of the array values. 

#### Ստեղծեք 10 չափանի numpy array, հաշվեք array-ի mean, median, standard deviation և variance։

In [16]:
arr = np.arange(10)
np.mean(arr), np.median(arr), np.std(arr), np.var(arr)

(4.5, 4.5, 2.8722813232690143, 8.25)

#### 20. Calculate the weighted average of the following array: np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]) using weights np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]). 

#### Հաշվեք տրված array-ի կշռված միջինը՝ np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])` օգտագործելով np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) weight-երը։

In [19]:
arr = np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])
weights = np.arange(1,arr.size+1)
print(weights)
np.average(arr, weights=weights)

[ 1  2  3  4  5  6  7  8  9 10]


13.654545454545454

#### 21. Sort the rows of the following numpy array in an increasing order: np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]). 

#### Աճման կարգով դասավորեք տրված numpy array-ի տողերը՝ np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]):

In [20]:
arr = np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]])
np.sort(arr, axis=1)

array([[1, 2, 4, 6],
       [0, 1, 2, 6],
       [1, 4, 4, 9]])

#### 22. Create the following numpy arrays and calculate the dot product between a and b. 

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։

$$a = \begin{bmatrix} 3 & 6 & 7 \\ 5 & -3 & 0  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [21]:
a = np.array([[3, 6, 7], [5, -3, 0]])
b = np.array([[1, 1], [2, 1], [3, -3]])
np.dot(a, b)

array([[ 36, -12],
       [ -1,   2]])